[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
    "cd ../..",
    "npm install -g pnpm@8.15.0",
    "pnpm config set frozen-lockfile false",
    "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
    "cd ../..",
    "pnpm build --filter @modern-erp/core-api",
    "pnpm --filter @modern-erp/database generate"
]

[start]
cmd = "cd services/core-api && node dist/index.js"