[build]
builder = "nixpacks"
buildCommand = "cd ../.. && npx pnpm@8 install --no-frozen-lockfile && npx pnpm@8 --filter @modern-erp/database generate && npx pnpm@8 build --filter @modern-erp/core-api"

[deploy]
startCommand = "cd services/core-api && node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"

[[services]]
name = "core-api"
internalPort = 3001

[services.envs]
NODE_ENV = "production"
DATABASE_URL = "${{POSTGRESQL.DATABASE_URL}}"
REDIS_URL = "${{REDIS.REDIS_URL}}"