[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm@8 && cd ../.. && pnpm install --no-frozen-lockfile && pnpm build --filter @modern-erp/core-api && pnpm --filter @modern-erp/database generate"

[deploy]
startCommand = "cd services/core-api && node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"

[[services]]
name = "core-api"
internalPort = 3001

[services.envs]
NODE_ENV = "production"
DATABASE_URL = "${{POSTGRESQL.DATABASE_URL}}"
REDIS_URL = "${{REDIS.REDIS_URL}}"