[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm@8 && cd ../.. && pnpm install --no-frozen-lockfile && pnpm build --filter @modern-erp/api-gateway"

[deploy]
startCommand = "cd services/api-gateway && node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30

[[services]]
name = "api-gateway"
internalPort = 8080

[services.envs]
NODE_ENV = "production"
CORE_API_URL = "${{CORE_API.RAILWAY_PRIVATE_URL}}"
MCP_URL = "${{MCP_ORCHESTRATOR.RAILWAY_PRIVATE_URL}}"
FACTORY_API_URL = "${{FACTORY_OPS.RAILWAY_PRIVATE_URL}}"
ANALYTICS_API_URL = "${{ANALYTICS_ENGINE.RAILWAY_PRIVATE_URL}}"